import Head from "next/head";
import cmsClient from "../lib/cmsClient";
import { homeEntryQuery } from "../gql/home.gql";
import HomeBanner from "../components/home/HomeBanner";

export async function getStaticProps() {
  const params = {
    siteId: [2],
  };

  const data = await cmsClient.request(homeEntryQuery, params);

  return {
    props: {
      data,
    },
  };
}

export default function Home({ data: { entry: fieldHomeBannerKerotec } }) {
  return (
    <div className="">
      <Head>
        <title>KEROTEC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomeBanner content={fieldHomeBannerKerotec} />
      </main>

      <footer></footer>
    </div>
  );
}
