import Head from "next/head";
import { GetStaticProps } from "next";
import cmsClient from "../lib/cmsClient";
import { homeEntryQuery } from "../gql/home.gql";

export async function getStaticProps() {
  const params = {
    siteId: [2],
  };
  const data = await cmsClient.request(homeEntryQuery, params);

  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  console.log(data);

  return (
    <div className="">
      <Head>
        <title>KEROTEC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="text-green-400">TEST</div>
      </main>

      <footer></footer>
    </div>
  );
}
