import Head from "next/head";
import React from "react";
import Menu from "../nav/Menu";
import Header from "./Header";

const Layout = ({ seo, mainNav, children }) => {
  return (
    <>
      <Head>
        <title>KEROTEC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header mainNav={mainNav} />
      <main>{children}</main>

      <footer></footer>
    </>
  );
};

export default Layout;
